### ISSUE TITLE
第一章 锁:互斥锁与读写锁

### ISSUE THREAD

**Issue by A-linna** [rustcc/Rust_Atomics_and_Locks#100]
![image](https://github.com/rustcc/Rust_Atomics_and_Locks/assets/66893381/ad76e882-4896-47be-b88c-1499073e704b)

这里 锁定一个未解锁的mutex，未解锁 意味着已经上锁了，被其他线上锁定了 还怎么锁定成功呢
原文是 When a thread locks an unlocked mutex
翻译成 锁定一个 未上锁的mutex 是不是合适些

**Comment by fwqaaq** [comment]
@A-linna 你是对的，这里应该是**解锁**状态，这段还可以优化
