### ISSUE TITLE
错别字

### ISSUE THREAD

**Issue by anicetrip** [rustcc/Rust_Atomics_and_Locks#72]
Channel<T> 结构体、它的 Sync 实现、它的>心<函数以及它的 Drop 实现保持不变。
心 -> 创建

**Comment by anicetrip** [comment]
第五章 阻塞

**Comment by fwqaaq** [comment]
感谢🙏，你可以提一下 pr，或者缩小一下问题的范围

**Comment by anicetrip** [comment]
> 感谢🙏，你可以提一下 pr，或者缩小一下问题的范围

好，我学习一下怎么提pr，第五章翻译的很棒！比我自己硬翻强多了。

**Comment by anicetrip** [comment]
> 感谢🙏，你可以提一下 pr，或者缩小一下问题的范围

已提交

**Comment by fwqaaq** [comment]
@anicetrip 感谢
