### ISSUE TITLE
web需要可读性更高的代码段代码高亮

### ISSUE THREAD

**Issue by Fodesu** [rustcc/Rust_Atomics_and_Locks#91]
![图片](https://github.com/rustcc/Rust_Atomics_and_Locks/assets/75713465/eec6ebcc-1ec0-4127-acee-b86a8e840949)

**Comment by fwqaaq** [comment]
<img width="1034" alt="image" src="https://github.com/rustcc/Rust_Atomics_and_Locks/assets/82551626/1db04463-281f-48ed-a907-d7cf4b09f254">
跟随系统的
