### ISSUE TITLE
第三章total order的翻译讨论

### ISSUE THREAD

**Issue by hycinth22** [rustcc/Rust_Atomics_and_Locks#95]
现在翻译为 _总顺序_ ，
也许翻译为专有名词 _全序_ 比较好？但是又有另一个问题， 还有Single total order、Total Modification Order等应该如何翻译

**Comment by fwqaaq** [comment]
> This means that every single operation using SeqCst ordering within a program is part of a sin‐ gle total order that all threads agree on. This total order is consistent with the total modification order of each individual variable.

这里 total order 并不像离散数学中的“全序”关系，而且如果翻译成全序（似乎有点抽象），其它列举的词块也不好翻译，我暂时没有很好的想法，如果你有可以提出来💪

**Comment by hycinth22** [comment]
这里应该是一致的，只有在最强的SeqCst下这些并发操作才具有happen-before的全序关系，更弱的Order下只有部分操作之间存在偏序关系。
不过确实如果对没有学过离散的而言这么翻译会更抽象。

**Comment by fwqaaq** [comment]
可以统一一下，第一个保留英文，然后标下 C++ 出处的脚注感觉挺可以的。
